// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "VTestHarness__Syms.h"
#include "VTestHarness.h"
#include "VTestHarness___024unit.h"
void VTestHarness__Syms::VTestHarness__Syms_1(VTestHarness* topp) {
    __Vscope_TestHarness__chiptop__system__subsystem_pbus__buffer__monitor.configure(this, name(), "TestHarness.chiptop.system.subsystem_pbus.buffer.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_pbus__coupler_to_device_named_uart_0__fragmenter.configure(this, name(), "TestHarness.chiptop.system.subsystem_pbus.coupler_to_device_named_uart_0.fragmenter", "fragmenter", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_pbus__coupler_to_device_named_uart_0__fragmenter__monitor.configure(this, name(), "TestHarness.chiptop.system.subsystem_pbus.coupler_to_device_named_uart_0.fragmenter.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_pbus__coupler_to_slave_named_bootaddressreg__fragmenter.configure(this, name(), "TestHarness.chiptop.system.subsystem_pbus.coupler_to_slave_named_bootaddressreg.fragmenter", "fragmenter", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_pbus__coupler_to_slave_named_bootaddressreg__fragmenter__monitor.configure(this, name(), "TestHarness.chiptop.system.subsystem_pbus.coupler_to_slave_named_bootaddressreg.fragmenter.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_pbus__fixer__monitor.configure(this, name(), "TestHarness.chiptop.system.subsystem_pbus.fixer.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_pbus__monitor.configure(this, name(), "TestHarness.chiptop.system.subsystem_pbus.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_pbus__out_xbar.configure(this, name(), "TestHarness.chiptop.system.subsystem_pbus.out_xbar", "out_xbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_pbus__out_xbar__monitor.configure(this, name(), "TestHarness.chiptop.system.subsystem_pbus.out_xbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__coupler_from_bus_named_subsystem_fbus__widget__monitor.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.coupler_from_bus_named_subsystem_fbus.widget.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__coupler_to_bus_named_subsystem_cbus__widget__monitor.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.coupler_to_bus_named_subsystem_cbus.widget.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__fixer__monitor.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.fixer.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__fixer__monitor_1.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.fixer.monitor_1", "monitor_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__fixer__monitor_2.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.fixer.monitor_2", "monitor_2", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__system_bus_xbar.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.system_bus_xbar", "system_bus_xbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__system_bus_xbar__monitor.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.system_bus_xbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__system_bus_xbar__monitor_1.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.system_bus_xbar.monitor_1", "monitor_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__system_bus_xbar__monitor_2.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.system_bus_xbar.monitor_2", "monitor_2", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__buffer_1__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.buffer_1.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__buffer_1__monitor_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.buffer_1.monitor_1", "monitor_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__core.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.core", "core", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__core__PlusArgTimeout.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.core.PlusArgTimeout", "PlusArgTimeout", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__core__csr.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.core.csr", "csr", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__core__ibuf.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.core.ibuf", "ibuf", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__dcIF.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.dcIF", "dcIF", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__dcIF__replayq.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.dcIF.replayq", "replayq", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__dcache.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.dcache", "dcache", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__dcache__tlb.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.dcache.tlb", "tlb", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__fpuOpt.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.fpuOpt", "fpuOpt", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__frontend.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.frontend", "frontend", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__frontend__icache.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.frontend.icache", "icache", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__frontend__tlb.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.frontend.tlb", "tlb", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini", "gemmini", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__ex_controller.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.ex_controller", "ex_controller", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__ex_controller__cmd_q.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.ex_controller.cmd_q", "cmd_q", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__ex_controller__mesh.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.ex_controller.mesh", "mesh", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__ex_controller__mesh__mesh.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.ex_controller.mesh.mesh", "mesh", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__ex_controller__mesh__tagq.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.ex_controller.mesh.tagq", "tagq", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__ex_controller__unrolled_cmd_mod__q.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.ex_controller.unrolled_cmd_mod.q", "q", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__load_controller.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.load_controller", "load_controller", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__load_controller__cmd_tracker.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.load_controller.cmd_tracker", "cmd_tracker", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__mod.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.mod", "mod", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__mod_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.mod_1", "mod_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__mod_1__ex.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.mod_1.ex", "ex", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__mod_1__ldab_arb.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.mod_1.ldab_arb", "ldab_arb", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__reservation_station.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.reservation_station", "reservation_station", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad", "spad", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__acc_mems_0.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.acc_mems_0", "acc_mems_0", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__acc_mems_0__mem.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.acc_mems_0.mem", "mem", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__acc_mems_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.acc_mems_1", "acc_mems_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__acc_mems_1__mem.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.acc_mems_1.mem", "mem", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__buffer_1__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.buffer_1.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__buffer_2__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.buffer_2.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__buffer__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.buffer.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__mvin_scale_pixel_repeater.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.mvin_scale_pixel_repeater", "mvin_scale_pixel_repeater", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__reader__xactTracker.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.reader.xactTracker", "xactTracker", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__spad_mems_0.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.spad_mems_0", "spad_mems_0", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__spad_mems_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.spad_mems_1", "spad_mems_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__spad_mems_2.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.spad_mems_2", "spad_mems_2", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__spad_mems_3.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.spad_mems_3", "spad_mems_3", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__writer.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.writer", "writer", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__xbar.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.xbar", "xbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__xbar__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.xbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__xbar__monitor_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.xbar.monitor_1", "monitor_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__spad__zero_writer_pixel_repeater.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.spad.zero_writer_pixel_repeater", "zero_writer_pixel_repeater", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__store_controller.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.store_controller", "store_controller", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__store_controller__cmd_tracker.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.store_controller.cmd_tracker", "cmd_tracker", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__gemmini__tlb__tlbs_0.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.gemmini.tlb.tlbs_0", "tlbs_0", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__ptw.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.ptw", "ptw", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__tlMasterXbar.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.tlMasterXbar", "tlMasterXbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__tlMasterXbar__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.tlMasterXbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__tile__tlMasterXbar__monitor_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.tile.tlMasterXbar.monitor_1", "monitor_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__uartClockDomainWrapper__uart_0__monitor.configure(this, name(), "TestHarness.chiptop.system.uartClockDomainWrapper.uart_0.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__adapter.configure(this, name(), "TestHarness.ram.adapter", "adapter", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__buffer_1__monitor.configure(this, name(), "TestHarness.ram.buffer_1.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__buffer__monitor.configure(this, name(), "TestHarness.ram.buffer.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter.configure(this, name(), "TestHarness.ram.fragmenter", "fragmenter", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter_1.configure(this, name(), "TestHarness.ram.fragmenter_1", "fragmenter_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter_1__monitor.configure(this, name(), "TestHarness.ram.fragmenter_1.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter__monitor.configure(this, name(), "TestHarness.ram.fragmenter.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__rom__monitor.configure(this, name(), "TestHarness.ram.rom.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__serdesser__monitor.configure(this, name(), "TestHarness.ram.serdesser.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__srams__monitor.configure(this, name(), "TestHarness.ram.srams.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__xbar.configure(this, name(), "TestHarness.ram.xbar", "xbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__xbar__monitor.configure(this, name(), "TestHarness.ram.xbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    
    // Setup scope hierarchy
    
}
